---
name: GitHub custom action sample
description: Github custom action sample using Docker and Go
inputs:
  foo-input:
    description: "input of foo"
outputs:
  hoge-output:
    description: "output of hoge"
runs:
  using: docker
  image: Dockerfile
  env:
    FOO_INPUT: ${{inputs.foo-input}}
